revert commenting stuff

diff --git a/.github/workflows/nightly_build.yml b/.github/workflows/nightly_build.yml
--- a/.github/workflows/nightly_build.yml
+++ b/.github/workflows/nightly_build.yml
@@ -49,9 +49,7 @@ jobs:
           # WARNING: These scripts must be run in this order.
           # Poetry will use a different cached virtual environment once the main pyproject.toml
           # project-name is updated, which does not have dependencies installed.
-          # BASE_TAG="$(poetry run python ./scripts/ci/pypi_nightly_tag.py base)"
-          BASE_TAG="0.0.95.dev5"
-
+          BASE_TAG="$(poetry run python ./scripts/ci/pypi_nightly_tag.py base)"
           echo "base_tag=$BASE_TAG" >> $GITHUB_OUTPUT
           poetry run python ./scripts/ci/update_pyproject_name.py langflow-base-nightly base
           poetry run python ./scripts/ci/update_pyproject_version.py $BASE_TAG base
@@ -59,37 +57,36 @@ jobs:
           # This updates the dependency of langflow-base to langflow-base-nightly in {project_root}/pyproject.toml
           poetry run python ./scripts/ci/update_lf_base_dependency.py $BASE_TAG
 
-          # MAIN_TAG="$(poetry run python ./scripts/ci/pypi_nightly_tag.py main)"
-          MAIN_TAG="1.0.17.dev5"
+          MAIN_TAG="$(poetry run python ./scripts/ci/pypi_nightly_tag.py main)"
           echo "main_tag=$MAIN_TAG" >> $GITHUB_OUTPUT
           poetry run python ./scripts/ci/update_pyproject_version.py $MAIN_TAG main
           poetry run python ./scripts/ci/update_pyproject_name.py langflow-nightly main
 
-          # git add pyproject.toml src/backend/base/pyproject.toml
-          # git commit -m "Update version and project name in files"
+          git add pyproject.toml src/backend/base/pyproject.toml
+          git commit -m "Update version and project name in files"
 
-          # git tag -a $MAIN_TAG -m "Langflow nightly $MAIN_TAG"
-          # git push origin $MAIN_TAG || echo "Tag push failed. Check if the tag already exists."
+          git tag -a $MAIN_TAG -m "Langflow nightly $MAIN_TAG"
+          git push origin $MAIN_TAG || echo "Tag push failed. Check if the tag already exists."
           # TODO: notify on failure
 
-  # frontend-tests:
-  #   name: Run Frontend Tests
-  #   needs: create-nightly-tag
-  #   uses: ./.github/workflows/typescript_test.yml
-  #   with:
-  #     tests_folder: "tests/end-to-end"
-  #     ref: ${{ needs.create-nightly-tag.outputs.tag }}
-  #   secrets:
-  #     OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"
-  #     STORE_API_KEY: "${{ secrets.STORE_API_KEY }}"
+  frontend-tests:
+    name: Run Frontend Tests
+    needs: create-nightly-tag
+    uses: ./.github/workflows/typescript_test.yml
+    with:
+      tests_folder: "tests/end-to-end"
+      ref: ${{ needs.create-nightly-tag.outputs.tag }}
+    secrets:
+      OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"
+      STORE_API_KEY: "${{ secrets.STORE_API_KEY }}"
 
-  # backend-unit-tests:
-  #   name: Run Backend Unit Tests
-  #   needs: create-nightly-tag
-  #   uses: ./.github/workflows/python_test.yml
-  #   with:
-  #     python-versions: '["3.10", "3.11", "3.12"]'
-  #     ref: ${{ needs.create-nightly-tag.outputs.tag }}
+  backend-unit-tests:
+    name: Run Backend Unit Tests
+    needs: create-nightly-tag
+    uses: ./.github/workflows/python_test.yml
+    with:
+      python-versions: '["3.10", "3.11", "3.12"]'
+      ref: ${{ needs.create-nightly-tag.outputs.tag }}
 
   # Not making nightly builds dependent on integration test success
   # due to inherent flakiness of 3rd party integrations
@@ -104,7 +101,7 @@ jobs:
 
   release-nightly-build:
     name: Run Nightly Langflow Build
-    # needs: [frontend-tests, backend-unit-tests, create-nightly-tag]
+    needs: [frontend-tests, backend-unit-tests, create-nightly-tag]
     uses: ./.github/workflows/release_nightly.yml
     with:
       build_docker_base: true
