Add updates for base version

diff --git a/.github/workflows/release_nightly.yml b/.github/workflows/release_nightly.yml
--- a/.github/workflows/release_nightly.yml
+++ b/.github/workflows/release_nightly.yml
@@ -39,8 +39,72 @@ env:
   POETRY_VERSION: "1.8.2"
 
 jobs:
+  release-nightly-base:
+    name: Release Langflow Nightly Base
+    runs-on: ubuntu-latest
+    outputs:
+      version: ${{ steps.check-version.outputs.version }}
+    steps:
+      - name: Check out the code at a specific ref (e.g., nightly tag)
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ inputs.nightly_tag }}
+
+      - name: Install poetry
+        run: pipx install poetry==${{ env.POETRY_VERSION }}
+      - name: Set up Python 3.12
+        uses: actions/setup-python@v5
+        with:
+          python-version: "3.12"
+          cache: "poetry"
+      - name: Set up Nodejs 20
+        uses: actions/setup-node@v4
+        with:
+          node-version: "20"
+      - name: Verify Nightly Name and Version
+        run: |
+          name=$(poetry version | cut -d' ' -f1)
+          version=$(poetry version --short)
+          if [ "$name" != "langflow-nightly" ]; then
+            echo "Name $name does not match langflow-nightly. Exiting the workflow."
+            exit 1
+          fi
+          if [ "$version" != "${{ inputs.nightly_tag }}" ]; then
+            echo "Version $version does not match nightly tag ${{ inputs.nightly_tag }}. Exiting the workflow."
+            exit 1
+          fi
+      - name: Build project for distribution
+        run: make build base=true
+      - name: Test CLI
+        run: |
+          python -m pip install dist/*.whl
+          python -m langflow run --host 127.0.0.1 --port 7860 --backend-only &
+          SERVER_PID=$!
+          # Wait for the server to start
+          timeout 120 bash -c 'until curl -f http://127.0.0.1:7860/health_check; do sleep 2; done' || (echo "Server did not start in time" && kill $SERVER_PID && exit 1)
+          # Terminate the server
+          kill $SERVER_PID || (echo "Failed to terminate the server" && exit 1)
+          sleep 10 # give the server some time to terminate
+          # Check if the server is still running
+          if kill -0 $SERVER_PID 2>/dev/null; then
+            echo "Failed to terminate the server"
+            exit 1
+          else
+            echo "Server terminated successfully"
+          fi
+      - name: Publish to PyPI
+        env:
+          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
+        run: make publish base=true
+      - name: Upload Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: dist-base
+          path: dist
+
   release-nightly-main:
     name: Release Langflow Nightly Main
+    needs: [release-nightly-base]
     runs-on: ubuntu-latest
     outputs:
       version: ${{ steps.check-version.outputs.version }}
@@ -105,7 +169,7 @@ jobs:
   call_docker_build_base:
     name: Call Docker Build Workflow for Langflow Base
     if: ${{ inputs.build_docker_base == 'true' }}
-    needs: release-nightly-main
+    needs: [release-nightly-base]
     uses: ./.github/workflows/docker-build.yml
     strategy:
       matrix:
@@ -122,7 +186,7 @@ jobs:
   call_docker_build_main:
     name: Call Docker Build Workflow for Langflow
     if: ${{ inputs.build_docker_main == 'true' }}
-    needs: release-nightly-main
+    needs: [release-nightly-main]
     uses: ./.github/workflows/docker-build.yml
     strategy:
       matrix:
